### ISSUE TITLE
Tangle Explorer installation failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by Galman21** [jmcanterafonseca-iota/IOTA-Tangle-Node-Deployment#48]
I got this error when i type "./tangle-explorer.sh install":

>Creating an optimized production build...
>DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
>
>Recommendation: math.div(15, 16)
>
>More info and automated migrator: https://sass-lang.com/d/slash-div
>
>  ╷
>2 │ $ct-scales: ((1), (15/16), (8/9), (5/6), (4/5), (3/4), (2/3), (5/8), (1/1.618), (3/5), (9/16), (8/15), (1/2), (2/5), (3/8), (1/3), (1/4)) >!default;
>  │                    ^^^^^
>  ╵
>    node_modules/chartist/dist/scss/settings/_chartist-settings.scss 2:20  @import
>    node_modules/chartist/dist/scss/chartist.scss 1:9                      @import
>    src/index.scss 8:9                                                     root stylesheet
>
>DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
>
>Recommendation: math.div(8, 9)
>
>More info and automated migrator: https://sass-lang.com/d/slash-div
>
>  ╷
>2 │ $ct-scales: ((1), (15/16), (8/9), (5/6), (4/5), (3/4), (2/3), (5/8), (1/1.618), (3/5), (9/16), (8/15), (1/2), (2/5), (3/8), (1/3), (1/4)) >!default;
>  │                             ^^^
>  ╵
>    node_modules/chartist/dist/scss/settings/_chartist-settings.scss 2:29  @import
>    node_modules/chartist/dist/scss/chartist.scss 1:9                      @import
>    src/index.scss 8:9                                                     root stylesheet
>
>DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
>
>Recommendation: math.div(5, 6)
>
>More info and automated migrator: https://sass-lang.com/d/slash-div
>
>  ╷
>2 │ $ct-scales: ((1), (15/16), (8/9), (5/6), (4/5), (3/4), (2/3), (5/8), (1/1.618), (3/5), (9/16), (8/15), (1/2), (2/5), (3/8), (1/3), (1/4)) >!default;
>  │                                    ^^^
>  ╵
>    node_modules/chartist/dist/scss/settings/_chartist-settings.scss 2:36  @import
>    node_modules/chartist/dist/scss/chartist.scss 1:9                      @import
>    src/index.scss 8:9                                                     root stylesheet
>
>DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
>
>Recommendation: math.div(4, 5)
>
>More info and automated migrator: https://sass-lang.com/d/slash-div
>
>  ╷
>2 │ $ct-scales: ((1), (15/16), (8/9), (5/6), (4/5), (3/4), (2/3), (5/8), (1/1.618), (3/5), (9/16), (8/15), (1/2), (2/5), (3/8), (1/3), (1/4)) >!default;
>  │                                           ^^^
>  ╵
>    node_modules/chartist/dist/scss/settings/_chartist-settings.scss 2:43  @import
>    node_modules/chartist/dist/scss/chartist.scss 1:9                      @import
>    src/index.scss 8:9                                                     root stylesheet
>
>DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.
>
>Recommendation: math.div(3, 4)
>
>More info and automated migrator: https://sass-lang.com/d/slash-div
>
>  ╷
>2 │ $ct-scales: ((1), (15/16), (8/9), (5/6), (4/5), (3/4), (2/3), (5/8), (1/1.618), (3/5), (9/16), (8/15), (1/2), (2/5), (3/8), (1/3), (1/4)) >!default;
>  │                                                  ^^^
>  ╵
>    node_modules/chartist/dist/scss/settings/_chartist-settings.scss 2:50  @import
>    node_modules/chartist/dist/scss/chartist.scss 1:9                      @import
>    src/index.scss 8:9                                                     root stylesheet
>
>WARNING: 12 repetitive deprecation warnings omitted.
>
>Failed to compile.
>
>/usr/src/app/src/helpers/fetchHelper.ts
>TypeScript error in /usr/src/app/src/helpers/fetchHelper.ts(53,19):
>Object is of type 'unknown'.  TS2571
>
>    51 |             return json as U;
>    52 |         } catch (err) {
>  > 53 |             throw err.name === "AbortError" ? new Error("Timeout") : err;
>       |                   ^
>    54 |         } finally {
>    55 |             if (timerId) {
>    56 |                 clearTimeout(timerId);
>
>
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! explorer-client@1.0.0 build-internal: `craco build`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the explorer-client@1.0.0 build-internal script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     /root/.npm/_logs/2021-09-03T09_28_53_637Z-debug.log
>ERROR: "build-internal" exited with 1.
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! explorer-client@1.0.0 build: `run-s lint sass-lint build-internal`
>npm ERR! Exit status 1
>npm ERR! 
>npm ERR! Failed at the explorer-client@1.0.0 build script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
>
>npm ERR! A complete log of this run can be found in:
>npm ERR!     /root/.npm/_logs/2021-09-03T09_28_53_652Z-debug.log
>The command '/bin/sh -c npm run build' returned a non-zero code: 1
>ERROR: Service 'explorer-webapp' failed to build : Build failed

**Comment by peterokwara** [comment]
Yep, I can confirm I am getting this error. @obany I think some of the updates made on the https://github.com/iotaledger/explorer has brought this error when it comes to docker.

**Comment by obany** [comment]
This was due to the stricter typing of Errors in TypeScript 4.4, a fix has been pushed to the Explorer repo, so it should work now.

**Comment by peterokwara** [comment]
@Galman21 you can try test it now and see if it works. It works on my side.

**Comment by Galman21** [comment]
> This was due to the stricter typing of Errors in TypeScript 4.4, a fix has been pushed to the Explorer repo, so it should work now.

Now it works, thank you very much!!!
