### ISSUE TITLE
Optional autopeering or static peering for Hornet mainnet

### ISSUE THREAD

**Issue by peterokwara** [jmcanterafonseca-iota/IOTA-Tangle-Node-Deployment#55]
## Description

Allow to choose autopeering or static peering when deploying Hornet for mainnet

## Motivation

At the moment only autopeering is supported when deploying Hornet for mainnet. It would be good to support both options autopeering and static peering

## Requirements

Write a list of what you want this feature to do.

1. Option to add static multiaddress when running the installation command.
2. Able to connect to mainnet via autopeering (as it currently happens)

## Open questions (optional)

Have the bash script modify the config.json or have a separate config.json for autopeering...

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by jmcanterafonseca-iota** [comment]
I think this issue is not an issue, the feature is already available @peterokwara

**Comment by peterokwara** [comment]
I just tested it out.

I ran 

`./hornet.sh install`

And autopeering was enabled by default.

![image](https://user-images.githubusercontent.com/6847405/136331318-0f80338a-2664-4b5d-8d8f-7b5c9501e71e.png)
![image](https://user-images.githubusercontent.com/6847405/136331433-034e2717-50c0-423d-a71c-f8fade010214.png)

And the node synced with mainnet successfully.
