### ISSUE TITLE
Private tangle install command failure.

### ISSUE THREAD

**Issue by ABresting** [jmcanterafonseca-iota/IOTA-Tangle-Node-Deployment#68]
## Bug description

Command failure while running the private tangle install script.

## Docker and docker-compose version

Which version of Docker and docker-compose are you running?

- Docker version: 20.10.12

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu
- RAM: 1 GB
- Cores: 1
- Device: Ubuntu VM from digital ocean

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1.  clone one-click-tangle github repo
2.  install dependencies like docker and compose
3. got to "~/one-click-tangle/hornet-private-net/" directory and run "./private-tangle.sh install"

## Expected behaviour

Normally a private tangle with a node, a spammer and a COO should be deployed and running.

## Actual behaviour

the script exited with an error.

## Errors

root@ubuntu-s-1vcpu-1gb-blr1-01:/one-click-tangle/hornet-private-net# ./private-tangle.sh install
Setting permissions for Hornet...
Stopping containers...
62bdb6c710c48ea6b3dd6334c1f6caadbc33ecc093ca2e27d527cdb486c3e8cc
Pulling coo              ... done
Pulling node             ... done
Pulling spammer          ... done
Pulling node-autopeering ... done
Generating an initial snapshot...
Creating hornet-private-net_node_run ... done
ERROR: 1
root@ubuntu-s-1vcpu-1gb-blr1-01:~/one-click-tangle/hornet-private-net# 

Also, inside the key-pair.txt file, the following was produced:

tool not found.

pwd-hash:            generates a scrypt hash from your password and salt
p2pidentity-gen:     generates a p2p identity private key file
p2pidentity-extract: extracts the p2p identity from the private key file
ed25519-key:         generates an ed25519 key pair
ed25519-addr:        generates an ed25519 address from a public key
jwt-api:             generates a JWT token for REST-API access
snap-gen:            generates an initial snapshot for a private network
snap-merge:          merges a full and delta snapshot into an updated full snapshot
snap-info:           outputs information about a snapshot file
snap-hash:           calculates the sha256 hash of the ledger state inside a snapshot file
bench-io:            benchmarks the IO throughput
bench-cpu:           benchmarks the CPU performance
db-migration:        migrates the database to another engine
db-hash:             calculates the sha256 hash of the ledger state of a database
db-health:           checks the health status of the database
db-split:            split a legacy database into `tangle` and `utxo`
coo-fix-state:       applies the latest milestone in the database to the coordinator state file

**Comment by jmcanterafonseca-iota** [comment]
this now should be fixed by forcing Hornet 1.0.5 as the image , please check @ABresting

**Comment by ABresting** [comment]
Issue resolved, `docker ps` output observed:
CONTAINER ID   IMAGE                   COMMAND         CREATED          STATUS          PORTS                                                                                             NAMES
1894da8ded9e   gohornet/hornet:1.0.5   "/app/hornet"   23 minutes ago   Up 23 minutes   0.0.0.0:8081->8081/tcp, 0.0.0.0:14265->14265/tcp, 1883/tcp, 0.0.0.0:15600->15600/tcp, 14626/udp   node1
1c504673d14b   gohornet/hornet:1.0.5   "/app/hornet"   23 minutes ago   Up 23 minutes   1883/tcp, 8081/tcp, 14265/tcp, 15600/tcp, 14626/udp                                               spammer
64583c015725   gohornet/hornet:1.0.5   "/app/hornet"   23 minutes ago   Up 23 minutes   1883/tcp, 8081/tcp, 14265/tcp, 15600/tcp, 14626/udp                                               coo
55b35d4a9799   gohornet/hornet:1.0.5   "/app/hornet"   23 minutes ago   Up 23 minutes   1883/tcp, 8081/tcp, 14265/tcp, 15600/tcp, 0.0.0.0:14626->14626/udp                                node-autopeering
