### ISSUE TITLE
Tangle Mainnet installation fails

### ISSUE THREAD

**Issue by imranmehdi5511** [jmcanterafonseca-iota/IOTA-Tangle-Node-Deployment#83]
mran@imran:~/one-click-tangle$ docker container ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
imran@imran:~/one-click-tangle$ cd hornet-mainnet
chmod +x hornet.sh
./hornet.sh install
Stopping hornet...
Removing hornet ... done
Cleaning up previous DB files
Cleaning up previous P2P files
Cleaning up previous snapshot files
Setting permissions for Hornet...
Configuring autopeering ...
Creating hornet ... done
imran@imran:~/one-click-tangle/hornet-mainnet$ ./hornet.sh info
Command not Found.
Installs Hornet version:  1.2.1
usage: hornet.sh [install||start|stop] -p <peer_multiAdress>
imran@imran:~/one-click-tangle/hornet-mainnet$ ./hornet.sh start
Install Hornet first with './hornet.sh install'
imran@imran:~/one-click-tangle/hornet-mainnet$ ./hornet.sh start
Install Hornet first with './hornet.sh install'
imran@imran:~/one-click-tangle/hornet-mainnet$ ./hornet.sh start
Install Hornet first with './hornet.sh install'
imran@imran:~/one-click-tangle/hornet-mainnet$

**Comment by jmcanterafonseca-iota** [comment]
this was related to the Docker images change from gohornet to iotaledger
