### ISSUE TITLE
Private hornet-based Tangle: docker-compose not working

### ISSUE THREAD

**Issue by akov800** [jmcanterafonseca-iota/IOTA-Tangle-Node-Deployment#84]
When trying to install the private Tangle network, the docker-compose file is not working.
I found out that the "gohornet/hornet" Docker Hub image used for the nodes is no longer available. I tried to fix this issue using the "iotaledger/hornet" image, but did not succeed: https://hub.docker.com/r/iotaledger/hornet

My question is if there is any intentions on updating this docker-compose file, updating and adapting it to the new Docker Hub images for hornet-based nodes. 

Thank you in advance!

**Comment by jmcanterafonseca-iota** [comment]
this is fixed now, thank you!
